name: key-editor
description: A github action that edits the specified key of TOML or JSON files 

inputs:
  files:
    description: "List of file paths separated by new lines"
    required: true
  key:
    description: "The key of the TOML/JSON file to change"
    required: true
  content:
    description: "The string to set the specified key to"
    required: true

runs:
  using: composite
  steps:
    - name: Convert paths to array
      shell: bash
      run: |
        echo "${{ inputs.files }}" > file-paths.txt
        FILE_ARRAY=()
        while IFS= read -r line; do
          trimmed_line=$(echo "$line" | sed 's/[[:space:]]*$//')
          if [[ -n "$trimmed_line" ]]; then
            FILE_ARRAY+=("$trimmed_line")
          fi
        done < file-paths.txt
        printf "%s\n" "${FILE_ARRAY[@]}" > file_paths_env.txt

    - name: Write to file keys
      shell: bash
      run: |
        KEY="${{ inputs.key }}"
        CONTENT="${{ inputs.content }}"
        echo "Processed file paths:"
        FILE_ARRAY=()
        while IFS= read -r line; do
          FILE_ARRAY+=("$line")
        done < file_paths_env.txt

        printf '%s\n' "${FILE_ARRAY[@]}"

        for file in "${FILE_ARRAY[@]}"; do
          echo "Processing: '$file'"
          if [[ -f "$file" ]]; then
            if [[ "$file" == *.json ]]; then
              jq --indent 4 ".\"$KEY\" = \"$CONTENT\"" "$file" > tmp.json && mv tmp.json "$file"
            elif [[ "$file" == *.toml ]]; then
              if [[ "$RUNNER_OS" == "Windows" ]]; then
                sed -i -E "s/^$KEY\s*=\s*\"[^\"]+\"/$KEY = \"$CONTENT\"/" "$file"
              else
                awk -v content="$CONTENT" -v key="$KEY" '$0 ~ "^" key " *= *\".*\"$" { $0 = key " = \"" content "\"" }1' "$file" > tmp.toml && mv tmp.toml "$file"
              fi
            fi
          else
            echo "$file is an invalid path"
          fi
        done

branding:
  icon: file
  color: orange
