name: version-bumper
description: A github action that bumps the version of TOML or JSON files

inputs:
  file-paths:
    description: "List of file paths separated by new lines"
    required: true
  version:
    description: "A specific version to set, defaults to git tag"
    required: false

runs:
  using: composite
  steps:
    - name: Convert paths to array
      shell: bash
      run: |
        echo "${{ inputs.file-paths }}" > file-paths.txt
        FILE_ARRAY=()
        while IFS= read -r line; do
          trimmed_line=$(echo "$line" | sed 's/[[:space:]]*$//')
          if [[ -n "$trimmed_line" ]]; then
            FILE_ARRAY+=("$trimmed_line")
          fi
        done < file-paths.txt
        printf "%s\n" "${FILE_ARRAY[@]}" > file_paths_env.txt

    - name: Get version from tag
      shell: bash
      run: |
        if [[ -n "${{ inputs.version }}" ]]; then
          VERSION="${{ inputs.version }}"
        else
          VERSION="${GITHUB_REF#refs/tags/v}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Write to file versions
      shell: bash
      run: |
        echo "Processed file paths:"
        FILE_ARRAY=()
        while IFS= read -r line; do
          FILE_ARRAY+=("$line")
        done < file_paths_env.txt

        printf '%s\n' "${FILE_ARRAY[@]}"

        for file in "${FILE_ARRAY[@]}"; do
          echo "Processing: '$file'"
          if [[ -f "$file" ]]; then
            if [[ "$file" == *.json ]]; then
              jq --indent 4 ".version = \"$VERSION\"" "$file" > tmp.json && mv tmp.json "$file"
            elif [[ "$file" == *.toml ]]; then
              if [[ "$RUNNER_OS" == "Windows" ]]; then
                sed -i -E "s/^version\s*=\s*\"[^\"]+\"/version = \"$VERSION\"/" "$file"
              else
                awk -v newver="$VERSION" '/^version *= *".*"$/ {$0 = "version = \"" newver "\""}1' "$file" > tmp.toml && mv tmp.toml "$file"
              fi
            fi
          else
            echo "$file is an invalid path"
          fi
        done

branding:
  icon: file
  color: orange
