name: Action Test
on: 
  workflow_dispatch:
  push:
    paths:
      - '**.yml'
  pull_request:
    paths:
      - '**.yml'

defaults:
  run:
    shell: bash

jobs:
  test1:
    uses: ./.github/workflows/env.yml
    with:
      content: "2.0.0"
      key: "version"
      files: |
        ./tests/test.json
        ./tests/test.toml

  test2:
    uses: ./.github/workflows/env.yml
    with:
      content: "very cool"
      key: "other"
      files: |
        ./tests/test.json
        ./tests/test.toml
          
      
      
